### ISSUE TITLE
Checker infos sensibles

### ISSUE THREAD

**Issue by Alicia-bites** [ELKAMINA/42_transcendance#100]
Faire bien attention à pas retourner des infos sensible dans l'API

- le hash du mot de passe
- l'email de l'user
- les mots de passe hashés des salons
- si l'utilisateur a activé où non la 2FA
- le secret du 2FA

**Comment by ELKAMINA** [comment]
Update du 27/08
Changements faits dans le backend pour ne renvoyer que les infos non sensibles pour :
- Les chan : envoi des données sans Key
- Les users : envoi des données sans : Hash/rtHash/email/Two factor authentication secret

Je la laisse ouvert au cas où des trucs chelous apparaissent
