### ISSUE TITLE
2fa activated / desactivated

### ISSUE THREAD

**Issue by Alicia-bites** [ELKAMINA/42_transcendance#107]
### Étapes pour Reproduire:
1. Activer 2fa 
2. se delogger
3. se connecter
4. aller voir si 2fa est toujours activé

### Comportement Attendu:
il devrait être toujours activé
### Comportement Actuel:
le 2fa est désactivé

**Comment by ELKAMINA** [comment]
Update du 21/08 :
C'est résolu. Le problème venait de la mise à jour des données et states de l'utilisateur
Changements faits dans le component "Security"

Branche créée : issues/issue_107
