### ISSUE TITLE
création d'un compte / authentification avec 42

### ISSUE THREAD

**Issue by Alicia-bites** [ELKAMINA/42_transcendance#108]
### Étapes pour Reproduire:
1. Je crée un compte avec pour login 'amarchan'
2. Je me delog
3. Je crée un compte avec 42 (pour moi le login sera aussi 'amarchan' du coup

### Comportement Attendu:
impossible de se log car un compte avec ce login existe deja

### Comportement Actuel:
possible de se log, et même que ca te log sur le premier compte créé  avec le login 'amarchan' --> DANGER usurpation de compte

**Comment by ELKAMINA** [comment]
Ok c'est corrigé, on ne peut se co ac login pareil que celui de OAuth et message d'erreur affiché
