### ISSUE TITLE
auth & websockets

### ISSUE THREAD

**Issue by Alicia-bites** [ELKAMINA/42_transcendance#11]
Deux tabs, deux users.

Tab1 -> usr1
Tab2 -> usr2

Si je rafraichis la tab de usr1, ca delog usr2 et met usr1 à la place !

**Comment by ELKAMINA** [comment]
A priori, c'est normal et logique car le cookie est écrasé et remplacé par celui existant 
A retester et revérifier au cas ou

**Comment by Alicia-bites** [comment]
c'est bien normal
