### ISSUE TITLE
Check in back user who is requested mute/unmute or ban/deban

### ISSUE THREAD

**Issue by Alicia-bites** [ELKAMINA/42_transcendance#111]
- le user doit etre admin
- le user qui est mute/unmute ou ban/unbanned ne doit pas être le meme que le user qui fait la request (on ne peut pas se deban / unmute soi-meme)

**Comment by ELKAMINA** [comment]
Update du 23/08 au soir :

All good, tout a été fait sur la branche [issues/issue_99] car pour moi, ce sont deux sujets liés
commit = 3ad1fe11d5682f10720b404d6bb29599148ebe8d
