### ISSUE TITLE
[ ALL ] : Authentication : Add limit for the nickname

### ISSUE THREAD

**Issue by ELKAMINA** [ELKAMINA/42_transcendance#114]
### Description du Problème:
(Décrivez le problème ici)

### Étapes pour Reproduire:
1. 
2. 
3. 

### Autre issue liée 
(Mettez "#idIssue")

**Comment by BarrierAntho** [comment]
Fix in the commit:
- 6be1615d632d7f435a3c15157df46ecb211e5766
