### ISSUE TITLE
Error on creation of public channel

### ISSUE THREAD

**Issue by BarrierAntho** [ELKAMINA/42_transcendance#117]
### Description du Problème:
Error when creation of a channel.

### Commit de test
15681d4930976df521e924f4dec968f1eb39a999

### Pré-requis
- No channel except the default one `WelcomeChannel`

### Étapes pour Reproduire:
1. Open a web browser and connect to `localhost:3000`.
2. Signup with `UserNameA`.
3. Open a **private** web browser and connect to `localhost:3000`.
4. Signup with `UserNameB`.
5. As `UserNameA`, make a friend request to `UserNameB`.
6. As `UserNameB`, accept the friend request from `UserNameA`.
7. As `UserNameA`, go to the `ChatPage`.
8. Click on the button `Create Channel`.
9. Define the following settings:
    - Channel name = `Test`
    - Users = [`UnserNameB`]
    - Type = `public`
10. Click on the button `Create Channel`.

### Comportement Attendu:
Creation of the channel.

### Comportement Actuel:
Error in the inspector and in the application.

### Capture d'Écran:
<img width="439" alt="Capture d’écran 2023-08-22 à 10 55 38" src="https://github.com/ELKAMINA/42_transcendance/assets/72570614/e5fc34ee-777e-4ee2-b3d0-8153e2c47a02">

<img width="782" alt="Capture d’écran 2023-08-22 à 10 36 49" src="https://github.com/ELKAMINA/42_transcendance/assets/72570614/d01b7fbf-b54c-49f8-a5c3-da78aabb763f">

### Informations Supplémentaires:
J'ai faiiiiimmmmm

### Autre issue liée 
(Mettez "#idIssue")

**Comment by Alicia-bites** [comment]
fixed
