### ISSUE TITLE
[ issues/issues_99 ] : Channels - Banned : A DEVELOPPER QUAND JE FINIS TESTS SUR ROLES

### ISSUE THREAD

**Issue by ELKAMINA** [ELKAMINA/42_transcendance#119]
![image](https://github.com/ELKAMINA/42_transcendance/assets/79459419/e3fbf46f-10a3-43b4-96f9-bbc9a4534cb5)

![image](https://github.com/ELKAMINA/42_transcendance/assets/79459419/b781ecac-f162-4578-a398-774b22f9f3ed)

**Comment by ELKAMINA** [comment]
A retester et essayer de reproduire

**Comment by Alicia-bites** [comment]
fix 79ba94426e966f3bba3075f06aae87dae1cf92ca
