### ISSUE TITLE
[ issues/issue_99 ] : Channels : When deleting a public channel - USER IS A MEMBER

### ISSUE THREAD

**Issue by ELKAMINA** [ELKAMINA/42_transcendance#120]
### Description du Problème:
when the owner deletes a chan, and if one of the member is on the page of page at the same moment, at the deletion, error appears in the browser

### Étapes pour Reproduire:
1. Connect with user1
2. user1 creates a public channel with at least two users (here user2 and user3)
3. user1 sends some messages
4. user2 connects and go to chat
5. user2 go to the channel that user1 created 
6. user1 deletes the chan
7. user2 gets an error trigerred in his page

### Capture d'Écran:

STEP 1: FILLING THE FORM
USER 1 SCREEN
![image](https://github.com/ELKAMINA/42_transcendance/assets/79459419/4c47bd6d-6576-4fef-b51d-2e53aaea1f3b)

STEP 2:  CREATING THE CHAN WITH JAMIE AND ARRIBA
USER 1 SCREEN

![image](https://github.com/ELKAMINA/42_transcendance/assets/79459419/b5d824aa-4ada-4ad4-8381-8ecd46edfeef)

STEP 3 : SENDING SOME MESSAGES 
USER 1 SCREEN
![image](https://github.com/ELKAMINA/42_transcendance/assets/79459419/72e81979-dcc3-4bc9-90f3-cb17281fe128)

STEP 4: CONNECTION WITH USER 2
USER 2 SCREEN
<img width="717" alt="image" src="https://github.com/ELKAMINA/42_transcendance/assets/79459419/83df49a7-92c7-4d94-9756-f71866bb4460">

STEP 5 : USER 2 sends messages
USER 2 SCREEN 
<img width="1406" alt="image" src="https://github.com/ELKAMINA/42_transcendance/assets/79459419/fb72f841-b83a-406d-b58f-855d21a9b819">

STEP 6: USER 1 DELETES CHANNEL ERROR
USER 1 SCREEN
![image](https://github.com/ELKAMINA/42_transcendance/assets/79459419/d73adafb-4207-47a8-8ac9-fcec8761e61a)

![image](https://github.com/ELKAMINA/42_transcendance/assets/79459419/c7ac7097-c4f6-4626-93f6-72c3c687feb2)

STEP 7: THE CHANNEL IS STILL DISPLAYED FOR USER 2  && THE SERVER CRASHES

<img width="751" alt="image" src="https://github.com/ELKAMINA/42_transcendance/assets/79459419/338057ab-076e-4b3c-9b95-8677ea128d44">

![image](https://github.com/ELKAMINA/42_transcendance/assets/79459419/459a0726-602b-42a8-857f-dc316e6bbd58)

### Autre issue liée 
(Mettez "#idIssue")

**Comment by Alicia-bites** [comment]
fix f01786dfab6b9278f0349da141aa827c34406dc0
