### ISSUE TITLE
[ issues/issues_99 ] : Channels : Public channels with password 

### ISSUE THREAD

**Issue by ELKAMINA** [ELKAMINA/42_transcendance#121]
### Description du Problème:
As a member added by the owner to a public channel protected with a password, when i go to channel and clicks on that channel. A dialog box is displayed and an error appears into the browser's console 

### Étapes pour Reproduire:
1. Connects with user 1
2. create a public channel protected with password (members: user2)
3. connects with user 2
4. go to chat then clicks on channel juste created by user 1
5. ERROR 1 : The displayed channel is wrong (in the screen shot below, the displayed channel is cersei while the public channel is "PublicChannelWithPassword"
6. ERROR 2: try to fill the password input 

NOTA BENE: theses ERROR are also displayed when we refresh the owner page and try to get the channel

### Comportement Attendu:
NO error in the browser's console and the right channel is displayed

### Comportement Actuel:
error displayed in the console and the wrong channel is displayed

### Capture d'Écran:

FROM USER 2 SCREEN (who is just a MEMBER)
<img width="733" alt="image" src="https://github.com/ELKAMINA/42_transcendance/assets/79459419/6e8b6a0b-d389-4cd9-b8bd-e23de54ccd60">

FROM USER 1 (THE OWNER ) SCREEN:

![image](https://github.com/ELKAMINA/42_transcendance/assets/79459419/1eb0793e-77d9-4307-a365-b845f096dd49)
 
### Autre issue liée 
(Mettez "#idIssue")

**Comment by Alicia-bites** [comment]
fix b2913b9aeaef3adb28186c9a950778f47bcbe4c4

**Comment by Alicia-bites** [comment]
probably fixed by other fix
