### ISSUE TITLE
[ issues_issue99 ] : Channels : password field still appears after deleting channel

### ISSUE THREAD

**Issue by ELKAMINA** [ELKAMINA/42_transcendance#122]
### Description du Problème:
As owner of the chan, when i delete the chan, It is well deleted but the dialog box appears after the deletion 

### Étapes pour Reproduire:
1. Connects with user1
2. Go to chat interface
3. Create a public channel protected by password 
4. Delete the channel

### Comportement Attendu:
Channel is deleted and nothing is displayed on the screen

### Comportement Actuel:
channel is deleted but the dialog box that suggests to enter the password appears after 

### Capture d'Écran:

STEP 1 : CREATING THE PUBLIC CHANNEL PROTECTED BY PASSWORD 

![image](https://github.com/ELKAMINA/42_transcendance/assets/79459419/67b8d1c7-ef0f-4fb7-a9f9-bff2e19333cb)

STEP 2 : DELETING THE CHANNEL

![image](https://github.com/ELKAMINA/42_transcendance/assets/79459419/38dfa5d9-8a16-40c3-ad7e-225f3ba03d5c)

STEP 3 : THE CHANNEL IS DELETED BUT THE DIALOG BOX FOR ENTERING THE PASSWORD APPEARS

![image](https://github.com/ELKAMINA/42_transcendance/assets/79459419/a9231baf-fe54-44fe-b305-82f2f38254fc)

![image](https://github.com/ELKAMINA/42_transcendance/assets/79459419/330c21e2-40c0-474c-a213-bf02accaaaa6)

### Autre issue liée 
(Mettez "#idIssue")

**Comment by Alicia-bites** [comment]
fix b2913b9aeaef3adb28186c9a950778f47bcbe4c4

**Comment by Alicia-bites** [comment]
FIX : 2a90ee493ef56f4e736c7ad5e0ff3e088330abe7
MY NEMESIS IS DEAD
