### ISSUE TITLE
[ issues/issue_99 ] : Channels - Update owners 

### ISSUE THREAD

**Issue by ELKAMINA** [ELKAMINA/42_transcendance#123]
### Description du Problème:
As user 1 owner of a public channel, i update owners of this channel giving the ownership to user2.
I can still delete the channel 

### Étapes pour Reproduire:
1. Connects with user 1
2.  create a public channel
3. change ownership and give it to user 2
4. Database is all good and informations are updated
5. the user1 can still delete the channel even if he has not the ownership

### Comportement Attendu:
Error message to forbid the deletion as it appears for the members

### Comportement Actuel:
the user can still delete the channel

### Capture d'Écran:

![image](https://github.com/ELKAMINA/42_transcendance/assets/79459419/116d0d81-bf6e-4514-be0e-f50ad081b29a)

![image](https://github.com/ELKAMINA/42_transcendance/assets/79459419/85a73b0c-7de6-4144-a42d-b68c8b380ea8)

![image](https://github.com/ELKAMINA/42_transcendance/assets/79459419/7da1b1d0-0f6d-4748-b79d-784448092278)

![image](https://github.com/ELKAMINA/42_transcendance/assets/79459419/187eb788-a2b6-42ca-af98-f792a36abf95)

![image](https://github.com/ELKAMINA/42_transcendance/assets/79459419/16ca96f6-5170-4f34-836f-cfa49d449866)

### Informations Supplémentaires:

Piste : MAYBE SOME FETCHING INFORMATION ABOUT THE CHANNEL IN THE FRONT OR REDUX ISN'T GETTING CALLED AT THE RIGHT PLACE 

### Autre issue liée 
(Mettez "#idIssue")

**Comment by Alicia-bites** [comment]
fix b2913b9aeaef3adb28186c9a950778f47bcbe4c4
