### ISSUE TITLE
[ issues/issues_99] : Channels : PUBLIC CHANNEL WITH PASSWORD - PASSWORD CAN BE EMPTY

### ISSUE THREAD

**Issue by ELKAMINA** [ELKAMINA/42_transcendance#124]
### Description du Problème:
I can create a public channel protected with password, with password empty

### Étapes pour Reproduire:
1. Connects with user1
2. Create a public channel protected with password 
3. Fill the form and let the password empty

### Comportement Attendu:
Error to remind the user to fill the password input

### Comportement Actuel:
No error, we can create the channel with a password empty

### Autre issue liée 
(Mettez "#idIssue")

**Comment by Alicia-bites** [comment]
fix 505ff93ef02d4202ee6dd3f234f556e7c1e6436f
