### ISSUE TITLE
[ issues/issues_99] : Channels : GIVING OWNERSHIP TO ANOTHER USER DOESN'T UPDATE ITS FRONT WITH THE HEIR IN REAL TIME

### ISSUE THREAD

**Issue by ELKAMINA** [ELKAMINA/42_transcendance#125]
### Description du Problème:

As owner of channel, i give ownsership to another user.
I have to refresh to see the heir appearing

### Étapes pour Reproduire:
prequisite : user1 is owner of a channel

1. Connects with user1
2. go the chat and clicks on channel (where i am owner)
3. give ownership to another member

### Comportement Attendu:
the new owner of the channel sees his window changing immedialtely with the "heir" appearing

### Comportement Actuel:
i need to refresh to page of the new owner to see the heir 

### Autre issue liée 
(Mettez "#idIssue")

**Comment by Alicia-bites** [comment]
fix b2913b9aeaef3adb28186c9a950778f47bcbe4c4
