### ISSUE TITLE
[ issues/issue_99 ] : Channels : As owner of chan, i give admin permissions to a member, it isn't displayed in real-time

### ISSUE THREAD

**Issue by ELKAMINA** [ELKAMINA/42_transcendance#126]
### Description du Problème:
As owner of chan, i give admin permissions to a member, it isn't displayed in real-time
### Étapes pour Reproduire:
prequisites : user1 has created a channel with user2 as member
1. user1 give admin rights to user2
2. user2 doesn't see the admin menu in the header of the conversation
3. SAME WHEN WE TAKE OFF THE ADMIN RIGHT FROM USER2, we don't see it in real time

### Autre issue liée 
(Mettez "#idIssue")

**Comment by Alicia-bites** [comment]
fix 25eeb9c72de10b7bd75fb1f8f395202dd79285f2
