### ISSUE TITLE
[ issues/issue99 ] : Channels : When trying to access a Public channel from searchBar

### ISSUE THREAD

**Issue by ELKAMINA** [ELKAMINA/42_transcendance#128]
### Description du Problème:

As a user, i go to chat and choose a channel from the list rendered.
NOTA BENE: i am not a member of this channel

### Étapes pour Reproduire:

prequisites : user connected and existing public channels
1. Go to chat
2. Click on the searchbar
3. clicks on public channel

### Capture d'Écran:

![image](https://github.com/ELKAMINA/42_transcendance/assets/79459419/bc203685-f130-4f4a-9b18-c9aa8ae5b9cd)

### Autre issue liée 
(Mettez "#idIssue")

**Comment by ELKAMINA** [comment]
Update du 23/08: Ajout d'une condition pour régler le problème sur la branche features/rooms par Alicia
RAF: merge avec master et tester

**Comment by Alicia-bites** [comment]
fix a57e5064ec295a90fe629d3a8afac39571095459
