### ISSUE TITLE
[ issues/issue_99 ] : Channels : a user that has been ban appears in the list suggested by "manage admin" menu

### ISSUE THREAD

**Issue by ELKAMINA** [ELKAMINA/42_transcendance#129]
### Description du Problème:

As owner of a channel, i ban a member then i click on "manage admins" and i can find this user in the list. I can even select hom and submit

### Étapes pour Reproduire:
prequisites: user1 is owner of a chan with 3 members

1. user1 bans user2
2. user1 click on "manage admins" menu and find the banned user (user 2) in the list
3. user1 can select user 2 and submit

### Comportement Attendu:

user banned should be grayed out

### Comportement Actuel:

user 2 is not grayed out and we can select him as admin

### Capture d'Écran:

USER 2 HERE REPRESENTS JAMIE_LANNISTER

![image](https://github.com/ELKAMINA/42_transcendance/assets/79459419/98753fd3-6e21-4b6c-850e-9bed4d78f3c4)

### Informations Supplémentaires:

Anyway, at the end of th day, when we go to the user's 2 window, a wonderful image is displayed to tell hum that he is banned

### Autre issue liée 

PRIORITY LOW LOW

**Comment by ELKAMINA** [comment]
Update du 23/08 

FINALEMENT C'EST dangereux car on peut faire des actions dans les menus des conversation même si le user a été BAN, KICK ou LEFT

Peux stp vérifier que tous les menus et les petites fenêtre qui s'affichent quand on clique sur les CHANNEL MENUS DANS LE HEADER,  se mettent bien à jour en cas de ban/kick ou LEAVE . Car je viens de tester le cas suivant : 

CERSEI_LANNISTER crée un channel avec Amina, Alicia et Anthony
Amina leaves the chan 
Cerser_LANNISTER peut quand même "make a heir" à Amina alors qu'elle s'est barrée du chan et ca cest dangeureux, car CERSEI NEST PLUS OWNER ET YA PLUS DE OWNER dans le chan
Je mets l'issue en PRIORITE HAUTE

**Comment by Alicia-bites** [comment]
fix 0ee9efdafffc3e8ca3d9497e67f084c3435c501b
