### ISSUE TITLE
[ issues/issues-99] Channels : when trying to delete a channel protected with password

### ISSUE THREAD

**Issue by ELKAMINA** [ELKAMINA/42_transcendance#130]
### Description du Problème:
While i was testing other functionalities in other channels, when i came to the first channel i created and which is protected by pwd  to delete it, i got this error 

### Étapes pour Reproduire:

prequisites : Connects with user having many types of channels
1. Do actions in all the channels then come back to one that is protected by a pwd and try to delete it
2. 
3. 

### Capture d'Écran:

![image](https://github.com/ELKAMINA/42_transcendance/assets/79459419/c5c835fe-ab18-44b2-9843-9b3359ab3ba9)

### Autre issue liée 
(Mettez "#idIssue")

**Comment by Alicia-bites** [comment]
fix ee05bc34b1740aa0aa905ada8fb90a36f85c61f6
