### ISSUE TITLE
[ issues/issues_99 ] : Channels : Kicking a user

### ISSUE THREAD

**Issue by ELKAMINA** [ELKAMINA/42_transcendance#133]
### Description du Problème:
when kicking a user, the list of user in "info about the user" isn't updated in real time 

### Étapes pour Reproduire:
1. 
2. 
3. 

### Autre issue liée 
(Mettez "#idIssue")

**Comment by BarrierAntho** [comment]
I will take the lead to this topic

**Comment by BarrierAntho** [comment]
fetchDisplayedChannel(roomId)

**Comment by Alicia-bites** [comment]
fix 3ea8ee7d625a71194b87561c095e9088fe80fdf7
