### ISSUE TITLE
[issues/issue_99]: Channels : when i leave a chan, it still appears on my sidebar

### ISSUE THREAD

**Issue by ELKAMINA** [ELKAMINA/42_transcendance#134]
### Capture d'Écran:

Jamie lannister has left "leaveRoles" channel but still can see it in the sidebar but can do nothing with it 
I understand that it what we're expecting and when clicking again on the channel, i has to display the ones that has left the chan. The problem is that, it doesn't appear in real-time

![image](https://github.com/ELKAMINA/42_transcendance/assets/79459419/6ffcc2c5-9478-4ca4-b4c2-35b2c13812b1)

**Comment by ELKAMINA** [comment]
Je comprends que c'est voulu car il ya les messages de "XXX has left the channel" 
Au temps pour moi

**Comment by Alicia-bites** [comment]
fix e37a6b14a1b708f795583a88b6ccb407c187fe7b
