### ISSUE TITLE
[issues/issue_99] : Channels : Double key in the sidebar 

### ISSUE THREAD

**Issue by ELKAMINA** [ELKAMINA/42_transcendance#136]
Je ne sais ni comment ni pourquoi, mais je me suis connectée avec cersei_lannister qui avait pleins de channels et discussion privée et j'ai eu ça 

![image](https://github.com/ELKAMINA/42_transcendance/assets/79459419/b42a07f9-062c-4e09-972a-be8035f51010)

**Comment by Alicia-bites** [comment]
avoir plein de channels (au moins 20)
se déconnecter et se redéconnecter

**Comment by Alicia-bites** [comment]
this bug was fixed
