### ISSUE TITLE
Channel : create channel impossible but no error shown

### ISSUE THREAD

**Issue by Alicia-bites** [ELKAMINA/42_transcendance#137]
### Description du Problème:
(Décrivez le problème ici)

### Étapes pour Reproduire:
1. open create channel pop up window
2. put in the name 'bowling in king's landing'
3. add one user
4. choose type public

### Comportement Attendu:
error message OR 'create channel' button should not be desable

### Capture d'Écran:
![image](https://github.com/ELKAMINA/42_transcendance/assets/51951741/ea51cca3-0eba-4093-afdf-8e1ec7f6ce5c)

**Comment by BarrierAntho** [comment]
Fixed in the commit:
- e8335ffc76e16e916d69bb98189340b8d87889cd
