### ISSUE TITLE
Bug 1 - Chat : 

### ISSUE THREAD

**Issue by ELKAMINA** [ELKAMINA/42_transcendance#14]
![Bug Chat](https://github.com/ELKAMINA/42_transcendance/assets/79459419/6e2b4ab2-822d-413e-b2d0-4304fa8d4ef1)

Je me co avec mon compte 42 - je choisis, Anthony pr parler avec dans le chat il me recupere bien Anthony mais ma photo de profil et quand je console.log ; displayed channel et current user dans Footer, jai ael-khat 2 fois au lieu de ael-khat t Anthony

**Comment by Alicia-bites** [comment]
fixed : 2e7b154b5fc5fa74ff36877a81081e2c1cedfe9d
