### ISSUE TITLE
IMPOSSIBLE TO CREATE CHANNEL

### ISSUE THREAD

**Issue by Alicia-bites** [ELKAMINA/42_transcendance#143]
### Étapes pour Reproduire:
1. Log in with user
2. Hit the button 'create channel'
3. fill in required fields
4. hit the button 'create channel'
5. ERROR in the front

### Comportement Attendu:
should be able to create channel

### Comportement Actuel:
error : error while creating channel =  Comparison issue between Friends and UserList

**Comment by ELKAMINA** [comment]
Corrigé sur commit : 86d5744e62526eaecee3ba7c84ce742d6ae8e400 de la branche [ issues/issue_143 ]
