### ISSUE TITLE
[Ban members] Ban and unban members kicks definitively the banned members

### ISSUE THREAD

**Issue by BarrierAntho** [ELKAMINA/42_transcendance#146]
### Description du Problème:
Ban and unban members kicks definitively the banned members from the channel.

### Étapes pour Reproduire:
1. Create a channel
   - Name: `test`
   - Members: [usernameA, usernameB, usernameC]
2. As `usernameA`, ban the member `usernameB` for unlimited time
3. As `usernameA`, unban the member `usernameB` for unlimited time

### Comportement Attendu:
In my mind, it should not kick definitively the member from the channel.
Or did you change the ban behavior ?

### Comportement Actuel:
Kicks definitively the banned members from the channel.

### Capture d'Écran:
- After the creation of the channel
<img width="420" alt="Capture d’écran 2023-08-29 à 21 25 09" src="https://github.com/ELKAMINA/42_transcendance/assets/72570614/afbc7dbd-5a88-4100-853b-d96c0dd0f936" title="test">  

- After banning a member
<img width="356" alt="Capture d’écran 2023-08-29 à 21 25 29" src="https://github.com/ELKAMINA/42_transcendance/assets/72570614/f968c4f5-e130-4b8d-b50b-1cd70b72a27e">  

- After unbanning a member
<img width="332" alt="Capture d’écran 2023-08-29 à 21 25 42" src="https://github.com/ELKAMINA/42_transcendance/assets/72570614/69e9f7e0-40f3-4f66-b35d-29d8bfa05830">  

### Autre issue liée 
(Mettez "#idIssue")

**Comment by BarrierAntho** [comment]
New branch `issues/issue_146` to try to fix the issue before to fix the ban with the timer

**Comment by Alicia-bites** [comment]
c'est normal :)
