### ISSUE TITLE
Bug2 - Chat : Possibilite de choisir deux fois le meme utilsateur pour le chat 

### ISSUE THREAD

**Issue by ELKAMINA** [ELKAMINA/42_transcendance#15]
![Bug Chat 2](https://github.com/ELKAMINA/42_transcendance/assets/79459419/b2f8ce8d-e115-4d65-8319-0f08a2836b04)

Issue liee a la #26

Qund je me deo, supprime le cache et relance le site, il me reprend mes conversations en double

**Comment by ELKAMINA** [comment]
Update du 18/08 :

Toujours d'actualité ssi le user est en dernier dans la liste 

![image](https://github.com/ELKAMINA/42_transcendance/assets/79459419/ee739f2c-19cc-4921-98ec-e95d0a3c21a6)

**Comment by BarrierAntho** [comment]
@ELKAMINA my bad

**Comment by Alicia-bites** [comment]
fix : 687c382e712395ab280a0ae6d45d13362ceb7636
