### ISSUE TITLE
End loop playing status

### ISSUE THREAD

**Issue by ELKAMINA** [ELKAMINA/42_transcendance#40]
# General
When the user is requesting a matchmaking, his status is changed from `Online` to `Playing` which also request a `socket` creation.
His status is used to avoid the user to play several game on different web session and/or web browser tab.
If the user tries to connect on different web session and/or web browser tab and tries to access to new matchmaking. Then he will not open a new `socket` for a new game.
However if the application crashs, his status will never be updated from `Playing` to `Online`. And the user will never be able to play anymore until a manual change of the user status in the database.

# Enhancement
At the login, check if the player is already playing. If not set his status to `Online`, otherwise let it as `Playing`

**Comment by BarrierAntho** [comment]
Done in the game REFACTOR
