### ISSUE TITLE
Create a profile page for the users

### ISSUE THREAD

**Issue by Alicia-bites** [ELKAMINA/42_transcendance#5]
1. Des stats (telles que : victoires et défaites, rang et niveaux, hauts faits, etc.) doivent être affichées sur le profil de l’utilisateur.

2. Chaque utilisateur doit avoir un Match History (historique comportant les parties 1 contre 1, les niveaux et ainsi de suite). Toute personne loguée doit pouvoir le consulter.

3. Grâce à l’interface de chat, l’utilisateur doit pouvoir accéder aux profils d’autres joueurs.

**Comment by ELKAMINA** [comment]
C'est Ok pour les 3. Reste à valider le format entre nous et remplir avec les vraies données du/des match et du User
