### ISSUE TITLE
Set the rank at the user creation

### ISSUE THREAD

**Issue by BarrierAntho** [ELKAMINA/42_transcendance#56]
# General
At the user creation, his rank is set by default at 0.

# Enhancement
The newly user must have the latest rank + 1.

# Examples
- At the very begining, no user inside the database.
- At the very first user creation, the newly user will get the rank 1 because no user inside the database then user rank = 1
- At the second creation of user creation, the newly user will get the rank of the last rank (1) + 1

**Comment by ELKAMINA** [comment]
Update du 08/08:

Ok corrigé sur la branche [ issues/issue_56]
