### ISSUE TITLE
impossible d'uploader un avatar

### ISSUE THREAD

**Issue by Alicia-bites** [ELKAMINA/42_transcendance#6]

**Comment by ELKAMINA** [comment]
C'est corrigé. Pb : je ne récupérais pas correctement la photo et ne mettait pas à jour la bonne donnée dans le store Redux.

un autre Buug associé était : quand tu étais déja enregistré dans la DB et que tu voulais changer ta photo de profil lors du Signin, ca ne lupdatait pas. C'est corrigé également
