### ISSUE TITLE
[ features/Pong_v2 ]: Channels, private conv

### ISSUE THREAD

**Issue by ELKAMINA** [ELKAMINA/42_transcendance#60]
liée à l'issue 

User ael-khat recoit une demande d'amis de la part du user NGARANGANGA.
User ael-khat accepte la demande 
User ael-khat clique sur 'Channels' et cherche son nouvel ami NAGARANGAGNA et clique sur le channel
c'est le user ael-khat qui apparait dans la fenetre de chat 

![image](https://github.com/ELKAMINA/42_transcendance/assets/79459419/8062a68a-dd3e-46f3-b090-9fcd3f2a454b)

**Comment by Alicia-bites** [comment]
fix : 5acec84a209a1dd42c2842e7872de191b75763bd
