### ISSUE TITLE
[Sigin-SignUp] Error if signup with small password

### ISSUE THREAD

**Issue by BarrierAntho** [ELKAMINA/42_transcendance#61]
# Use case
- Create a new user `toto`.
- Create a new password `toto`

# Issue
Message error from the nest/react

**Comment by ELKAMINA** [comment]
Résolu :

Message d'erreur s'affiche désormais en bas du champs de Sign 

Corrigé sur : branche [ issues/issue_71] sur commit : 5fc457130164981a08b6e6e11c422cee65ff1c94
