### ISSUE TITLE
[ features/Pong_v2 ] : Channels - Récupération des users dans la searchBar

### ISSUE THREAD

**Issue by ELKAMINA** [ELKAMINA/42_transcendance#65]
# Use case
- Connects with user1 in a window
- Connects with user2 in a window
- user 2 adds user1
- user1 accepts user2
- user2 goes to the channels page and checks for user1 in the searchbar 

![Screenshot from 2023-08-03 13-20-45](https://github.com/ELKAMINA/42_transcendance/assets/79459419/6defd961-a051-45ba-a3cb-e560db6171b6)

![Screenshot from Screencast from 08-03-2023 01:21:47 PM webm](https://github.com/ELKAMINA/42_transcendance/assets/79459419/d361e1fe-c3cb-4d2a-889e-c16ff8236222)

# Issue
searchbar doesn't  get the user1

**Comment by Alicia-bites** [comment]
fix : 3c97b76bd1ae7d7ea79d39a303603b9b964184ae
