### ISSUE TITLE
[ features/Pong_v2 ]: Channel - Error concerning the websockets

### ISSUE THREAD

**Issue by ELKAMINA** [ELKAMINA/42_transcendance#66]
# Use case
- Connect with a user and go to channel

Browser : Mozilla Firefox
![Screenshot from 2023-08-03 13-27-53](https://github.com/ELKAMINA/42_transcendance/assets/79459419/f5412a5a-4e70-4afa-b789-21d1c93ac052)

# Issue
Error concerning the websockets

**Comment by Alicia-bites** [comment]
fix: 841b0dc6e4faa2ab02835f90101fc9e4dbbbd533

**Comment by Alicia-bites** [comment]
fix: 841b0dc6e4faa2ab02835f90101fc9e4dbbbd533
