### ISSUE TITLE
[ Toutes les branches ] : Channels - Message 404 NOT FOUND pour la route : http....channel/displayed

### ISSUE THREAD

**Issue by ELKAMINA** [ELKAMINA/42_transcendance#67]
<img width="742" alt="image" src="https://github.com/ELKAMINA/42_transcendance/assets/79459419/0b7062d0-86d1-48df-a54d-c6e20cbc69a4">

**Comment by ELKAMINA** [comment]
Piste pour ALICIA : 

Dans le fichier : client/src/components/Navbat.tsx 
j'ai commenté un useEffect que tu avais utilisé : 
 useEffect(() => {
    dispatch(fetchDisplayedChannel("WelcomeChannel")); // reset displayed channel to WelcomeChannel
     }, [logout]); 

et je n'ai plus l'erreur 

/!\ A VOIR QUELLES CONSEQUENCES CELA PEUT AVOIR SUR TON CODE

**Comment by Alicia-bites** [comment]
happens only if the database is not seeded, because the default channel 'welcome channel' isn't yet in the db
