### ISSUE TITLE
Chat One to One - Pas le bon affichage pour le nom du User

### ISSUE THREAD

**Issue by ELKAMINA** [ELKAMINA/42_transcendance#7]
ex: J' ai un user sous le nom de "Amina" qui envoie un message au user "ael-khat"
Sur la page de chat de "ael-khat",  sur la barre des messages reçus, c'est "ael-khat" qui est affichée et non "Amina"
<img width="1376" alt="image" src="https://github.com/ELKAMINA/42_transcendance/assets/79459419/f19b6555-fb24-4bb4-93e6-aa936780461a">
<img width="733" alt="image" src="https://github.com/ELKAMINA/42_transcendance/assets/79459419/921d4a28-e043-4a1f-b029-fea69d476bbc">

**Comment by Alicia-bites** [comment]
fixed b6f6e9dbe8f2c8385255740b6b0b5c6ea792b2c6
