### ISSUE TITLE
[Home] Not responsive welcome page

### ISSUE THREAD

**Issue by BarrierAntho** [ELKAMINA/42_transcendance#79]
### Description du Problème:
Les textes 'Pong', 'Play' et 'Leaderboard' ne s'adaptent pas en fonction de la taille de l'écran.

### Étapes pour Reproduire:
1. Se mettre dans la page welcome
2. Changer la taille de l'écran avec les outils de développement du navigateur.

### Comportement Attendu:
Les textes devraient s'adapter

### Comportement Actuel:
Les textes sont de la même taille que sur un écran normal

### Autre issue liée 
(Mettez "#idIssue")

**Comment by ELKAMINA** [comment]
Update 08/08: 

Done : Typos and icons are now responsive depending on the screen size
