### ISSUE TITLE
#KICK OUT 

### ISSUE THREAD

**Issue by Alicia-bites** [ELKAMINA/42_transcendance#88]
### Description du Problème:
Le user qui est kicked out n'est pas 'éjectée' du channel.

### Étapes pour Reproduire:
1. Ouvrir deux fenetres, se connected avec deux users différents. Ils doivent être amis.
2. Créer un CHANNEL dont l'un est créateur (il sera donc automatiquement admin) et l'autre membre.
3. Le user qui est créateur (et donc admin) doit kick le user membre.

### Comportement Attendu:
le user qui est kicked devrait être "envoyé" sur le "WelcomeChannel"

### Comportement Actuel:
cf ci-dessus baby

### Capture d'Écran:
////

### Informations Supplémentaires:
j'aime les cornichons

### Autre issue liée 
(Mettez "#idIssue")

**Comment by BarrierAntho** [comment]
Question pour le kick:
Quand une personne est kicked, il faut la renvoyer sur le channel "WelcomeChannel", mais on ne le voit pas dans la liste ? J'ai compris que c'était nécéssaire pour faire fonctionner les channels ? Mais je vois plusieurs cas:
1. Si une personne n'a aucun channel dans sa liste, renvoyer la personne dans le channel "WelcomeChannel" a du sens.
2. Mais si la personne a déjà des channels actifs, est-ce que ça ne serait pas plus logique de renvoyer la personne vers le premier channel que la personne qu'elle a dans sa liste ?

De plus je ne vois pas trop ce qui doit être fait côté back ?
Est-ce que la dite personne "Kicked" est totalement supprimée du channel et donc on la voit plus dans les membres du channel et la personne kicked ne voit plus le channel dans sa liste ?

**Comment by Alicia-bites** [comment]
1. Renvoie sur le Welcome Channel quel que soit le cas de figure.
Si tu renvoie sur le premier channel de la liste, il est possible que ce channel soit protégé par un mot de passe, ce qui rendrait tout compliqué.

2. Pour le back, il faut en effet faire une request au back pour supprimer le user de la liste des membres ET admin si admin ET muted si muted, etc...

**Comment by BarrierAntho** [comment]
Fixed: 2b7a134c150046613485dd88b02cb00308635cc0
