### ISSUE TITLE
#MUI-AUTOCOMPLETE MESS

### ISSUE THREAD

**Issue by Alicia-bites** [ELKAMINA/42_transcendance#89]
### Description du Problème:
Au secours
Dans la search bar de la page "chat", quand on sélectionne un "friend" , gros pâté cf screenshot

### Étapes pour Reproduire:
1. aller sur /chat
2. cliquer sur la searchbar
3. selectionner un user/friend
4. regarder la console du navi
5. pleurer sa daronne

### Comportement Attendu:
pas de caca

### Comportement Actuel:
plein de caca

### Capture d'Écran:
![image](https://github.com/ELKAMINA/42_transcendance/assets/51951741/febd349c-cc02-4eae-ad73-958ccb8fe631)

### Autre issue liée 
(Mettez "#idIssue")

**Comment by ELKAMINA** [comment]
Update c'est fix sur issues/issues_89. Commit : 5f514ec932fdb5cf2f7de91e1229a3941171b86a

**Comment by ELKAMINA** [comment]
Update du 27/08 
Résolu pour de bon : Le problème était dans "my options" props
je vous expliquerai en détail plus tard si ça vous interesse car j'ai la flemme actuellement en ce dimanche d'été pluvieux
