### ISSUE TITLE
#BLOCK USER FROM CHANNEL

### ISSUE THREAD

**Issue by Alicia-bites** [ELKAMINA/42_transcendance#90]
### Description du Problème:
Quand un user est bloqué, il se passe des trucs moches.

### Étapes pour Reproduire:
1. 
2. 
3. 

### Comportement Attendu:
Quand un user est bloqué, il devrait se passer des trucs beaux.
### Comportement Actuel:
Quand un user est bloqué, il se passe des trucs moches.

### Capture d'Écran:
tu veux pas voir ca cousin

### Informations Supplémentaires:
il est possible de voir des pinguins en Irlande

### Autre issue liée 
(Mettez "#idIssue")

**Comment by ELKAMINA** [comment]
All good. A jour dans la branche issues/issue_12_90_BIS 
issue liée à #12
