### ISSUE TITLE
[ issues/issues_87 ] : When trying to create channel

### ISSUE THREAD

**Issue by ELKAMINA** [ELKAMINA/42_transcendance#92]
### Description du Problème:
When i try to create a channel, the avatar of one of my conversation is appearing on the dialog box of "create channel", also the block icon and game icon

### Étapes pour Reproduire:

1. Go to channel page
2. clicks on "create channel"
pre-requisite : Having a chat page with someone before clicking on "create channel"

### Capture d'Écran:

<img width="1347" alt="image" src="https://github.com/ELKAMINA/42_transcendance/assets/79459419/2143e23b-0805-4d03-9848-a8c095b9429e">

### Autre issue liée 
(Mettez "#idIssue")

**Comment by Alicia-bites** [comment]
ah ouuuais impossible de changer ca, j'ai essayé par tous les moyens (notamment changer le z-index. Si quelqu'un a une idée de piste, n'hésitez pas

**Comment by ELKAMINA** [comment]
Okkkkkk, a voir plus tard

**Comment by Alicia-bites** [comment]
En fait ca le faisait pour tous les boutons du Header.

Le component <Button> de MUI casse les couilles car il refuse d'aller en arrière-plan. En tout cas je n'ai pas trouvé comment dans la doc. Si quelqu'un sait le faire, n'hésitez pas à me le signaler.

EN ATTENDANT -- 
J'ai fix en créant un state dans le channelSlice qui est set à "true" si la 'create-channel' pop-up window est ouverte, et "false" si elle est fermée. Comme ca si c'est true, je fais tout simplement disparaitre les boutons du Header.

fix : f68f2e0c7a4a8e67ff79655ebb7ae15cb45ca190

**Comment by Alicia-bites** [comment]
erratum
fix : 679ee13f8f68704d32cf4a304e0cd0c31ab88ff6
