### ISSUE TITLE
[ All branches ] : Creating channel : Problem with the "users" input

### ISSUE THREAD

**Issue by ELKAMINA** [ELKAMINA/42_transcendance#96]
### Description du Problème:
When i try to create a channel, in the input users, if i click on one user then i click again on the same user to delete it. The user is added anyway

### Étapes pour Reproduire:
Pre-requisites : A user that has at least 3 users as friends

1. Connect with a user
2. Click on chat section
3. Click on CREATE CHANNEL BUTTON
4. Name the channel
5. Add his 3 friends
6. Deletes one of the 3 friends from the list by clicking again
7. The channel is created with the 3 friends

### Comportement Attendu:
The channel created should have only 2 friends added in the chan

### Comportement Actuel:
The 3 friends are added to the chan 

### Capture d'Écran:

First screenshot : i try to create channel, and firstly i select all my friends : 

<img width="1427" alt="image" src="https://github.com/ELKAMINA/42_transcendance/assets/79459419/d0ed721a-1067-49fd-82b0-cafddb4d098e">

Second screenshot : i delete the last 

<img width="720" alt="image" src="https://github.com/ELKAMINA/42_transcendance/assets/79459419/b6e572b0-69e1-45d2-988c-519e327de001">

Third screenshot : i create the channel

<img width="1428" alt="image" src="https://github.com/ELKAMINA/42_transcendance/assets/79459419/ac9d6c74-edf3-4f30-af8b-27f7c13fd50b">

Last screenshot : i verify the members, i have all of them even the one i deleted

<img width="973" alt="image" src="https://github.com/ELKAMINA/42_transcendance/assets/79459419/c0cb3ec4-4305-4e12-8812-41c4fba21098">

**Comment by Alicia-bites** [comment]
fix : 494ce17105b6d2ecdca20ac1ae479c1cb2f77de0
