### ISSUE TITLE
[ All branches ] : Deleting channel : when channel is deleted, its window still appears 

### ISSUE THREAD

**Issue by ELKAMINA** [ELKAMINA/42_transcendance#97]
### Description du Problème:
when i delete a channel, its window still appears to the user 

### Étapes pour Reproduire:
Prequisites :
- A user that has Channels and is admin of theses channels
- A user that has at least 2 friends to create a channel

1. Connect with a user 
2. Go to chat section
3. Select a channel where the user is admin
4. Delete it 

### Comportement Attendu:
The user don't see the channel anymore

### Comportement Actuel:

The user still sees the channel window

### Capture d'Écran:
A venir 

### Autre issue liée 
(Mettez "#idIssue")

**Comment by Alicia-bites** [comment]
fix : e5e30f9b3ed2a198b16fbe3af3a7d095e7199fde
