### ISSUE TITLE
Refresh KP when adding a member

### ISSUE THREAD

**Issue by BarrierAntho** [ELKAMINA/42_transcendance#98]
### Description du Problème:
Lors de l'ajout d'un membre dans un channel multi-users, le user ajouté ne subit pas de refresh et donc ne voit pas le channel tant qu'il n'a pas refresh sa page manuellement.

### Étapes pour Reproduire:
1. En tant que UserA, créer un channel public multi-users en invitant UserB.
2. En tant que UserA,  ajoute le membre UserC.

### Comportement Attendu:
Le membre ajouté devrait voir le channel dans lequel il a été ajouté sans avoir à refresh manuellement.

### Comportement Actuel:
Voir description

### Informations Supplémentaires:
J'aime le veau...

### Autre issue liée 
(Mettez "#idIssue")

**Comment by Alicia-bites** [comment]
fix: f017c194a7eda2e3108267af072063ff5de272eb
